controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    orthrus_joint_state:
      type: joint_state_broadcaster/JointStateBroadcaster

    orthrus_joint_effort:
      type: effort_controllers/JointGroupEffortController

    orthrus_imu:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

orthrus_joint_effort:
  ros__parameters:
    joints:
      - LF_HAA 
      - LF_HFE 
      - LF_KFE 
      - LH_HAA 
      - LH_HFE 
      - LH_KFE 
      - RF_HAA 
      - RF_HFE 
      - RF_KFE 
      - RH_HAA 
      - RH_HFE 
      - RH_KFE 

orthrus_imu:
  ros__parameters:
    frame_id: base
    sensor_name: imu_sensor
    

