controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    orthrus_controller:
      type: orthrus_controller/OrthrusController

orthrus_controller:
  ros__parameters:
    sim_or_real: "real"
    

