controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    orthrus_gazebo_joint_state:
      type: joint_state_broadcaster/JointStateBroadcaster

    orthrus_gazebo_joint_effort_controller:
      type: effort_controllers/JointGroupEffortController

    orthrus_gazebo_imu:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

orthrus_gazebo_joint_effort_controller:
  ros__parameters:
    joints:
      - hip_RF_joint
      - leg1_RF_joint
      - leg2_RF_joint
      - hip_LF_joint
      - leg1_LF_joint
      - leg2_LF_joint
      - hip_RB_joint
      - leg1_RB_joint
      - leg2_RB_joint
      - hip_LB_joint
      - leg1_LB_joint
      - leg2_LB_joint

orthrus_gazebo_imu:
  ros__parameters:
    frame_id: imu_link
    sensor_name: imu_sensor



