controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    orthrus_gazebo_joint_state:
      type: joint_state_broadcaster/JointStateBroadcaster

    orthrus_gazebo_joint_effort_controller:
      type: effort_controllers/JointGroupEffortController

    orthrus_gazebo_imu:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

orthrus_gazebo_joint_effort_controller:
  ros__parameters:
    joints:
      - HAA_LF_joint
      - HFE_LF_joint
      - KFE_LF_joint
      - HAA_LH_joint
      - HFE_LH_joint
      - KFE_LH_joint
      - HAA_RF_joint
      - HFE_RF_joint
      - KFE_RF_joint
      - HAA_RH_joint
      - HFE_RH_joint
      - KFE_RH_joint

orthrus_gazebo_imu:
  ros__parameters:
    frame_id: body
    sensor_name: imu_sensor
    



