controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controller:
      type: effort_controllers/JointGroupEffortController

effort_controller:
  ros__parameters:
    joints:
      - hip_RF_joint
      - leg1_RF_joint
      - leg2_RF_joint
      - hip_LF_joint
      - hip_RB_joint
      - hip_LB_joint
      - leg1_LF_joint
      - leg1_RB_joint
      - leg1_LB_joint
      - leg2_LF_joint
      - leg2_RB_joint
      - leg2_LB_joint




