orthrus_controller:
  leg_joint_num:
    {
      type: int,
      default_value: 12,
      description: "Number of leg joint of the robot.",
    }
  leg_joint_names:
    {
      type: string_array,
      default_value:
        [
          LF_HAA,
          LF_HFE,
          LF_KFE,
          LH_HAA,
          LH_HFE,
          LH_KFE,
          RF_HAA,
          RF_HFE,
          RF_KFE,
          RH_HAA,
          RH_HFE,
          RH_KFE,
        ],
      description: "Joint name of legged robot",
    }

  imu_names:
    {
      type: string_array,
      default_value: [imu_sensor],
      description: "Joint name of legged robot",
    }
  imu_data_types:
    {
      type: string_array,
      default_value:
        [
          angular_velocity.x,
          angular_velocity.y,
          angular_velocity.z,
          linear_acceleration.x,
          linear_acceleration.y,
          linear_acceleration.z,
          orientation.w,
          orientation.x,
          orientation.y,
          orientation.z,
        ],
      description: "imu data type name of robot",
    }

  flag_names:
    {
      type: string_array,
      default_value: [flag],
      description: "Joint name of legged robot",
    }
  flag_data_types:
    {
      type: string_array,
      default_value:
        [
          enable_power,
          calibration_position
        ],
      description: "imu data type name of robot",
    }

  package_name:
    {
      type: string,
      default_value: "orthrus_interfaces",
      description: "Package name",
    }

  package_path:
    {
      type: string,
      default_value: "/home/evence/ros2_ws/src/orthrus_ros2_pack/orthrus_interfaces",
      description: "Path to package name",
    }
  
  sim_or_real:
    {
      type: string,
      default_value: "sim",
      description: "sim or real",
    }



